### ISSUE TITLE
Required approvals are not enforced on pull requests without reviews

### ISSUE THREAD

**Issue by uvsmtid** [Weetbix/configurable-required-approvals#62]
## Use case:

I'm trying to configure path-based approvals.

The repo has 0 required approvals by default (only automatic verifications, no humans involved).

But some files has to be protected by at least 1 required approval.

## Problem:

Apparently, the logic requires reviews != 0 to enforce required approvals:
https://github.com/Weetbix/configurable-required-approvals/blob/3bfaad3036ddd3e005cebf026795322f3fb85136/src/check-required-approvals.ts#L92

This means pull request for sensitive path can be merged without approvals because it has no reviews.

## Sample job config:

```yaml
name: required approvals

on:
    pull_request:
    pull_request_review:

permissions:
    checks: write
    pull-requests: read

jobs:
    required-approvals:
        runs-on: ubuntu-latest

        steps:
            -   name: check required approvals
                uses: weetbix/configurable-required-approvals@v1
                with:

                    requirements: |

                        -   patterns:
                                -   "file_requiring_0_approvals.txt"
                            requiredApprovals: 0

                        -   patterns:
                                -   "file_requiring_1_approvals.txt"
                            requiredApprovals: 1

                    github-token: ${{ secrets.GITHUB_TOKEN }}
```
