### ISSUE TITLE
Which `patterns` list takes precedence if more than one match?

### ISSUE THREAD

**Issue by uvsmtid** [Weetbix/configurable-required-approvals#63]
# Problem

This intention (how the implementation is supposed to work) is missing from the docs:
https://github.com/marketplace/actions/configurable-required-approvals

Which number of `requiredApprovals` will take precedence if more than one `patterns` match?

For example:

```yaml
# ...
    steps:
      - name: Check required approvals
        uses: weetbix/configurable-required-approvals@v1
        with:
          requirements: |
            - patterns:
                - "same_file_pattern/**/*"
              requiredApprovals: 1
            - patterns:
                - "same_file_pattern/**/*"
              requiredApprovals: 2

```

Will changes in `same_file_pattern/` require 1 or 2 approvals?
